apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dotnetcoreonk8s
  namespace: fire-ug
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotnetcoreonk8s
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50