apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-pv
  namespace: fire-ug
  labels:
    pv: log
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.101.4
    path: "/export/k8s/dotnetcoreonk8s/"
